import antfu from '@antfu/eslint-config'
import nuxtConfig from './.nuxt/eslint.config.mjs'

// Components here that declare a `title` *prop* and render it as a heading. Any
// other `title` lands on a DOM element as the browser's own tooltip — see the
// vue/no-restricted-syntax rule below.
const TITLE_PROP = 'cast-row|library-browser|media-slider|mpv-player|scroll-row|settings-section|v-card|v-expansion-panel|v-list-item'

export default antfu({
  vue: true,
  typescript: true,
  // The Rust/Tauri side owns its own formatting (rustfmt, generated schemas).
  // boot-diagnostics.js is deliberately ES5 and deliberately unbundled — every
  // modern rule here is one it has to break to do its job.
  // i18n/locales/* is generated by `bun run i18n` — 72 files of translation
  // values, rewritten wholesale on every run. Linting them only means the
  // generator has to satisfy a formatter as well as vue-i18n.
  ignores: ['src-tauri/**', 'app/boot-diagnostics.js', 'i18n/locales/**'],
}, {
  files: ['**/*.vue'],
  rules: {
    'vue/operator-linebreak': ['error', 'before'],
    // Vuetify's per-column slots are named `item.<key>`, which the rule reads as
    // a modifier on `item`. Vuetify's own docs say to allow it.
    'vue/valid-v-slot': ['error', { allowModifiers: true }],
    'vue/component-name-in-template-casing': ['error', 'kebab-case', {
      registeredComponentsOnly: false,
      ignores: [],
    }],
    // A `title` attribute is the *browser's* tooltip: an unstyled OS box, half a
    // second late, in the system font, and unreachable from a remote — and it
    // is the one tooltip `html.tv .v-tooltip { display: none }` in layers.css
    // cannot hide, so it is exactly the affordance a television must not get.
    // Use `v-tooltip:top="…"`, or a `<v-tooltip activator="parent" :text>`
    // child where the component has room for one.
    // Everything outside TITLE_PROP is flagged, components included: one that
    // doesn't consume the prop passes it straight to its root element, which is
    // how `v-btn`, `v-icon` and `v-slider` each grew a native tooltip.
    'vue/no-restricted-syntax': ['error', {
      selector: `VElement:not([rawName=/^(${TITLE_PROP})$/]) > VStartTag > VAttribute[directive=false][key.name='title']`,
      message: 'Native tooltip: use v-tooltip:top="…" instead of title="…".',
    }, {
      selector: `VElement:not([rawName=/^(${TITLE_PROP})$/]) > VStartTag > VAttribute[directive=true][key.name.name='bind'][key.argument.name='title']`,
      message: 'Native tooltip: use v-tooltip:top="…" instead of :title="…".',
    }],
  },
}, {
  rules: {
    'style/semi': ['error', 'never'],
    'no-console': 'warn',
    'arrow-parens': ['error', 'as-needed'],
    'ts/ban-ts-comment': 'off',
    'style/arrow-parens': 'off',
    'unused-imports/no-unused-vars': 'warn',
    'node/prefer-global/process': 'off',
  },
}, nuxtConfig())
