import antfu from '@antfu/eslint-config'
import nuxtConfig from './.nuxt/eslint.config.mjs'

export default antfu({
  vue: true,
  typescript: true,
  // The Rust/Tauri side owns its own formatting (rustfmt, generated schemas).
  // boot-diagnostics.js is deliberately ES5 and deliberately unbundled — every
  // modern rule here is one it has to break to do its job.
  // i18n/locales/* is generated by `bun run i18n` — 72 files of translation
  // values, rewritten wholesale on every run. Linting them only means the
  // generator has to satisfy a formatter as well as vue-i18n.
  ignores: ['src-tauri/**', 'app/boot-diagnostics.js', 'i18n/locales/**'],
}, {
  files: ['**/*.vue'],
  rules: {
    'vue/operator-linebreak': ['error', 'before'],
    // Vuetify's per-column slots are named `item.<key>`, which the rule reads as
    // a modifier on `item`. Vuetify's own docs say to allow it.
    'vue/valid-v-slot': ['error', { allowModifiers: true }],
    'vue/component-name-in-template-casing': ['error', 'kebab-case', {
      registeredComponentsOnly: false,
      ignores: [],
    }],
    // A `title` on a plain element is the *browser's* tooltip: an unstyled OS
    // box, half a second late, ignoring the theme, and no way to reach it from
    // a remote. Vuetify's is the app's own — `v-tooltip:top="…"` on the
    // element, and layers.css hides all of them on a television, which the
    // native one would have gone on showing. `title` on a component is a prop
    // (v-card, settings-section, …) and is untouched.
    'vue/no-restricted-syntax': ['error', {
      selector: 'VElement[rawName=/^[a-z][a-z0-9]*$/] > VStartTag > VAttribute[directive=false][key.name=\'title\']',
      message: 'Native tooltip: use v-tooltip:top="…" instead of title="…".',
    }, {
      selector: 'VElement[rawName=/^[a-z][a-z0-9]*$/] > VStartTag > VAttribute[directive=true][key.name.name=\'bind\'][key.argument.name=\'title\']',
      message: 'Native tooltip: use v-tooltip:top="…" instead of :title="…".',
    }],
  },
}, {
  rules: {
    'style/semi': ['error', 'never'],
    'no-console': 'warn',
    'arrow-parens': ['error', 'as-needed'],
    'ts/ban-ts-comment': 'off',
    'style/arrow-parens': 'off',
    'unused-imports/no-unused-vars': 'warn',
    'node/prefer-global/process': 'off',
  },
}, nuxtConfig())
