import type { LocaleObject } from '@nuxtjs/i18n'
import { readFileSync } from 'node:fs'
import process from 'node:process'
import { flag } from './app/utils/flag'
import i18nLocales from './i18n/i18n.locales.json'
import { version } from './package.json'
import vuetifyConfig from './vuetify.config'

const host = process.env.TAURI_DEV_HOST

// The list is generated (`bun run i18n:locales`) and read back as JSON, so the
// codes and text directions arrive as plain strings; the module's own types
// name them exactly.
const { defaultLocale, locales } = i18nLocales as { defaultLocale: LocaleObject['code'], locales: LocaleObject[] }

/**
 * Inlined rather than imported, because it has to run on a webview that
 * couldn't parse the bundle — see app/boot-diagnostics.js. A separate file
 * would be one more request that can fail on the way to explaining a failure.
 */
const bootDiagnostics = readFileSync(new URL('app/boot-diagnostics.js', import.meta.url), 'utf8')
  .replace('__VERSION__', version)

export default defineNuxtConfig({
  compatibilityDate: '2026-01-01',
  ssr: false,
  devtools: { enabled: false },

  modules: [
    '@vueuse/nuxt',
    '@unocss/nuxt',
    'vuetify-nuxt-module',
    '@nuxt/fonts',
    '@nuxt/eslint',
    '@pinia/nuxt',
    '@nuxtjs/i18n',
    '@nuxt/icon',
  ],

  /**
   * Every translated string lives in one catalog per language
   * (i18n/locales/<code>.json), all of it generated by `bun run i18n` — see
   * that script for the workflow, and scripts/i18n-locales.ts for where the
   * language list comes from (TMDB's, so the UI can't offer a language the
   * film data has nothing to say in).
   */
  i18n: {
    defaultLocale,
    locales,
    // No language in the URL. Prefixed routes exist so a search engine can
    // index one page per language and a person can share a localised link —
    // this app is a bundle behind a Tauri webview, with no canonical URL, no
    // crawler and no address bar, so it paid the cost and got nothing. The cost
    // was the Back button: every history entry carried a language, so stepping
    // back past a switch switched the language back.
    strategy: 'no_prefix',
    // Off because the app remembers the choice itself, in `ventic.locale` —
    // this module's own memory is a cookie, and a cookie on a `tauri://` origin
    // is not reliably kept. localStorage is where every other preference lives
    // and is what `app/utils/backup.ts` carries between machines. The restore
    // happens in app.vue.
    detectBrowserLanguage: false,
    // No `lazy` here: v10 dropped the option and lazy-loads unconditionally, so
    // `bun run build` still writes the 72 catalogs as separate chunks and only
    // the one in use is fetched.
  },
  runtimeConfig: {
    public: {
      TMDB_API: process.env.TMDB_API,
    },
  },
  css: [
    // The font itself, from a package rather than @nuxt/fonts: that module
    // resolves families over the network at build time, and a Flathub build has
    // none — it emitted no @font-face at all there, silently, while working
    // here. A dependency is vendored into the offline build like any other.
    '@fontsource-variable/roboto',
    '@/assets/css/layers.css',
  ],

  app: {
    head: {
      title: 'Ventic',
      charset: 'utf-8',
      // viewport-fit=cover is what makes env(safe-area-inset-*) report anything
      // at all — Android draws the app under the status and gesture bars
      // (enableEdgeToEdge in MainActivity.kt), and those insets are how the
      // chrome gets out from under them. See --safe-* in assets/css/layers.css.
      viewport: 'width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover',
      meta: [
        { name: 'format-detection', content: 'no' },
      ],
      link: [
        { rel: 'icon', href: '/logo.svg' },
      ],
      script: [
        { innerHTML: bootDiagnostics },
      ],
    },
  },

  /**
   * The only icons that aren't @mdi/js are the language picker's flags, and
   * they are inlined into the bundle rather than fetched: there is no Nitro
   * server behind a `tauri://` origin to serve them and no promise of a network
   * to reach api.iconify.design over. `clientBundle.scan` can't find them —
   * the name is computed per locale — so the list is built the same way the
   * page builds it.
   */
  icon: {
    provider: 'none',
    serverBundle: false,
    clientBundle: {
      icons: locales.flatMap(l => flag(l.language ?? '') || []),
    },
  },

  vuetify: {
    moduleOptions: {
      styles: { configFile: 'app/assets/css/settings.scss' },
      // Vuetify auto-imports a `useLayout` that collides with Nuxt's built-in
      // one, and warns about it on every dev boot. We only ever use these two.
      importComposables: ['useDisplay', 'useTheme'],
    },
    vuetifyOptions: vuetifyConfig,
  },

  // Tauri modules are auto-imported from here (see app/modules/tauri.ts).
  dir: {
    modules: 'app/modules',
  },

  imports: {
    presets: [
      {
        from: 'zod',
        imports: [
          'z',
          { name: 'infer', as: 'zInfer', type: true },
        ],
      },
    ],
  },

  router: {
    options: {
      scrollBehaviorType: 'smooth',
    },
  },

  eslint: {
    config: {
      standalone: false,
    },
  },

  experimental: {
    typedPages: true,
  },

  vite: {
    clearScreen: false,
    // Tauri expects TAURI_-prefixed env vars to reach the client.
    envPrefix: ['VITE_', 'TAURI_'],
    server: {
      strictPort: true,
      watch: {
        ignored: ['**/src-tauri/**'],
      },
    },
    optimizeDeps: {
      include: ['@mdi/js'],
    },
  },

  devServer: {
    host: host || '0.0.0.0',
  },

  hooks: {
    /**
     * Mobile is the one target that doesn't load the dev server directly: the
     * webview gets the frontend through Tauri's own `http://tauri.localhost`
     * proxy. Vite's HMR client dials the page's own origin, and a custom
     * protocol can't carry a WebSocket — so on Android the socket never opens.
     *
     * That shows up as a *styling* bug rather than a stale-reload one, because
     * UnoCSS generates utilities as it scans modules and ships everything past
     * the first request over HMR. No socket, no utilities, and the app renders
     * as good as unstyled with no way to reload it by hand.
     *
     * `server.ws.host`/`port` are the documented knob for this, but @nuxt/cli
     * blanks both (`attachViteHmrServer`) to pin the socket to its own dev
     * server — so point the *client* at the loopback address `adb reverse`
     * maps instead, after the CLI has had its say. `clientPort` is needed
     * because `tauri.localhost` has no port for Vite to reuse.
     */
    'vite:configResolved': config => {
      if (host && config.server?.ws)
        Object.assign(config.server.ws, { host, clientPort: 3000 })
    },
  },
})
