/**
 * Live TV: a playlist of channels, and deliberately nothing else.
 *
 * A channel is a name and a URL. Playing one needs no engine, no disk and no
 * swarm — it is the `Release.url` path the debrid and local-file features
 * already take (`startTorrent`'s `url` option), so the whole feature is a list
 * and a link. Nothing here touches the player.
 *
 * The list comes from an **M3U playlist**, which is what both halves of the
 * world speak: the free public indexes publish one, and every paid IPTV
 * subscription hands out one. An Xtream Codes panel is included in that — its
 * `get.php?…&type=m3u_plus` URL *is* an M3U, so pasting that needs no second
 * client and no credentials form.
 *
 * The same line as Sources: the app ships with no playlists, suggests none, and
 * bundles no directory of them. A playlist is a URL the user pastes.
 *
 * Left out on purpose, and each of them is a project rather than a function:
 * EPG (XMLTV) and a programme guide, catch-up and DVR, and the Xtream JSON API
 * with its VOD library. None is needed to watch a channel.
 */
import { fetch as tauriFetch } from '@tauri-apps/plugin-http'

/** One channel from a playlist. */
export interface Channel {
  /** Unique within a load, for list keys — playlists repeat names *and* URLs. */
  id: string
  name: string
  /** Whatever `tvg-logo` pointed at. Often absent, often a dead link. */
  logo: string
  /** `group-title`, or the last `#EXTGRP:`. '' in a playlist that has neither. */
  group: string
  url: string
}

/**
 * A playlist host is somebody's IPTV panel, not an addon server: it sends no
 * `Access-Control-Allow-Origin`, and a `tauri://` origin is bound by CORS like
 * any other page. So this one fetch goes through Rust, where that rule does not
 * exist — which is the whole reason `tauri-plugin-http` is a dependency.
 *
 * `bun run dev` has no Rust under it and falls back to the browser's fetch,
 * where only a playlist that does send the header will load. The *streams*
 * never come this way: mpv and ExoPlayer open the channel URL themselves.
 */
function get(url: string) {
  const f = '__TAURI_INTERNALS__' in globalThis ? tauriFetch : globalThis.fetch
  return f(url, { signal: AbortSignal.timeout(30_000) })
}

/** `tvg-id="x" group-title="A B"` — quoted values, so a space inside one is safe. */
const ATTR = /([\w-]+)="([^"]*)"/g

/** Anything at all that could be read as a name. */
const READABLE = /[\p{L}\p{N}]/u

/**
 * A line that names something to play. Requiring a scheme is what lets a
 * playlist with no `#EXTINF` at all — a bare list of URLs — still work, without
 * every stray line in a malformed file becoming a channel.
 */
const STREAM = /^[a-z][\w+.-]*:\/\//i

/**
 * One playlist -> its channels.
 *
 * Forgiving in the same way `parseSupporters` is, and for a stronger reason: a
 * playlist is generated by somebody else's panel, is tens of thousands of lines
 * long, and is riddled with rows that are not channels — `===== SPORTS =====`
 * headings drawn out of box characters are a house style over there. A row that
 * can't be read is dropped rather than taking the page down with it.
 */
export function parseM3u(text: string, from = '0'): Channel[] {
  const out: Channel[] = []
  let attrs: Record<string, string> = {}
  let title = ''
  // #EXTGRP applies to everything after it until the next one, unlike the
  // per-entry group-title attribute.
  let sticky = ''

  for (const raw of text.split('\n')) {
    const line = raw.trim()
    if (!line)
      continue

    if (line.startsWith('#EXTINF:')) {
      attrs = {}
      // Pulling the attributes out first leaves `-1 ,Name`, so the name is
      // simply what follows the comma — no counting quotes to find which comma
      // was the real one, and a comma inside an attribute value is already gone.
      const rest = line.slice(8).replace(ATTR, (_, key: string, value: string) => {
        attrs[key.toLowerCase()] = value
        return ''
      })
      const comma = rest.indexOf(',')
      title = comma < 0 ? '' : rest.slice(comma + 1).trim()
      continue
    }

    if (line.startsWith('#EXTGRP:')) {
      sticky = line.slice(8).trim()
      continue
    }

    // #EXTVLCOPT, #KODIPROP, comments: none of them ends the entry.
    if (line.startsWith('#'))
      continue

    if (!STREAM.test(line))
      continue

    // `url|User-Agent=…` is how a playlist smuggles request headers past a URL.
    // Nothing here can send them — mpv and ExoPlayer are handed the URL, not our
    // fetch — and left on the end they make the URL itself wrong.
    const url = line.split('|')[0]!.trim()
    const entry = attrs
    const name = entry['tvg-name'] || title || url
    // Consumed: a bare URL after this one is its own channel, not a second copy
    // of this one's attributes.
    attrs = {}
    title = ''

    if (!READABLE.test(name))
      continue

    out.push({
      id: `${from}:${out.length}`,
      name,
      logo: entry['tvg-logo'] ?? '',
      group: entry['group-title'] || sticky,
      url,
    })
  }
  return out
}

/**
 * What to show instead of the URL. An Xtream playlist carries the account's
 * username and password in its query string, and a settings list — read across
 * a room on a television — is the last place either belongs.
 */
export function playlistName(url: string) {
  try {
    const u = new URL(url)
    return u.host + (u.pathname === '/' ? '' : u.pathname)
  }
  catch {
    return url
  }
}

/**
 * What a favourite is filed under.
 *
 * The name, not the URL, for two reasons. An Xtream stream URL is
 * `…/username/password/12345.ts`, and a credential must not end up in a
 * localStorage map that travels in a backup. And a provider rotating its URLs —
 * which they do — would otherwise silently drop every favourite, while the name
 * survives it.
 *
 * ponytail: two channels sharing a name across two playlists are one favourite.
 * That reads as right more often than not ("ESPN is a favourite"); key it on
 * `playlist + name` the day someone wants them apart.
 */
export function channelKey(name: string) {
  return name.trim().toLowerCase()
}

/** Every group a channel named, for the filter. */
export function channelGroups(channels: Channel[]) {
  return [...new Set(channels.map(c => c.group).filter(Boolean))].sort((a, b) => a.localeCompare(b))
}

export function filterChannels(channels: Channel[], query: string, group: string) {
  const q = query.trim().toLowerCase()
  if (!q && !group)
    return channels
  return channels.filter(c =>
    (!group || c.group === group)
    && (!q || c.name.toLowerCase().includes(q)))
}

/**
 * Every configured playlist, merged and in the order they were added. One being
 * down costs its channels and not the page — the same deal `findReleases` gives
 * a source that doesn't answer.
 */
export async function fetchChannels(urls: string[]): Promise<Channel[]> {
  const results = await Promise.allSettled(urls.map(async (url, i) => {
    const res = await get(url)
    if (!res.ok)
      throw new Error($t('{playlist} answered HTTP {status}', { playlist: playlistName(url), status: res.status }))
    return parseM3u(await res.text(), String(i))
  }))

  const channels = results.flatMap(r => r.status === 'fulfilled' ? r.value : [])
  // Some channels is a working page. None, with something rejected, reads as an
  // empty playlist unless the reason is passed on.
  if (!channels.length) {
    const failed = results.find(r => r.status === 'rejected')
    // Rethrown as it came, not wrapped: `String(anError)` is "Error: …", and
    // the page shows `.message` — so wrapping put the word "Error" in front of
    // a sentence that already read as one.
    if (failed)
      throw failed.reason instanceof Error ? failed.reason : new Error(String(failed.reason))
  }
  return channels
}

/**
 * The same list, fetched once per session.
 *
 * ponytail: in memory only — a subscription's playlist changes about as often
 * as the subscription does, and the Live TV page is the only thing that reads
 * it. The refresh button in Settings is the upgrade path if that stops holding;
 * persisting it is not, since a large playlist is megabytes of localStorage.
 */
let cache: { key: string, channels: Channel[] } | null = null

export async function loadChannels(urls: string[], refresh = false) {
  const key = urls.join('\n')
  if (!refresh && cache?.key === key)
    return cache.channels
  const channels = await fetchChannels(urls)
  cache = { key, channels }
  return channels
}
