// Self-check for the Live TV playlist parser: `bun scripts/check-iptv.ts`.
//
// An M3U is generated by somebody else's IPTV panel, is tens of thousands of
// lines long, and reaches a user long before any build does. The parser's whole
// job is to get the readable rows out and drop the rest rather than take the
// page down, so that is what this holds — plus the two things about the *shape*
// of the feature that no compiler sees: the CORS bypass it depends on, and the
// ExoPlayer module without which every channel is unplayable on Android.
import assert from 'node:assert'
import { readFileSync } from 'node:fs'
import process from 'node:process'
import { channelGroups, channelKey, fetchChannels, filterChannels, isXtream, parseM3u, parseXtream, playlistName, xtreamChannels, xtreamUrl } from '../app/utils/iptv'
import './i18n-stub'

const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

// --- The rows a real playlist is made of --------------------------------------

const playlist = `#EXTM3U url-tvg="http://example.invalid/epg.xml"
#EXTINF:-1 tvg-id="one.us" tvg-logo="http://example.invalid/1.png" group-title="Sports",Channel One HD
http://example.invalid/live/one.m3u8
#EXTINF:-1 group-title="Sports",═══════════
http://example.invalid/live/divider
#EXTGRP:News
#EXTINF:-1,Channel Two
#EXTVLCOPT:http-user-agent=SomePlayer/1.0
http://example.invalid/live/two.ts|User-Agent=SomePlayer%2F1.0
#EXTINF:-1 tvg-name="Three, the third" tvg-logo="http://example.invalid/3.png",Ignored Title
http://example.invalid/live/three.m3u8
`

const channels = parseM3u(playlist)

assert.equal(channels.length, 3, 'a row of box characters is decoration, not a channel')
assert.deepEqual(channels.map(c => c.name), ['Channel One HD', 'Channel Two', 'Three, the third'])

// group-title wins where it exists; #EXTGRP carries on until the next one.
assert.deepEqual(channels.map(c => c.group), ['Sports', 'News', 'News'])

// A comma inside a quoted attribute must not be read as the one before the name.
assert.equal(channels[2]!.name, 'Three, the third')
// …and tvg-name beats the display title, which is where a panel puts its junk.
assert.equal(channels[2]!.logo, 'http://example.invalid/3.png')

// `url|User-Agent=…` smuggles request headers past a URL. Nothing here can send
// them, and left on the end they make the URL itself wrong.
assert.equal(channels[1]!.url, 'http://example.invalid/live/two.ts')
assert.equal(channels[1]!.logo, '', 'the previous entry\'s logo must not carry over')

// Ids are unique, or the grid renders one card for two channels.
assert.equal(new Set(channels.map(c => c.id)).size, 3)

// --- Playlists that are barely playlists --------------------------------------

// No #EXTINF at all: a bare list of URLs is still a list of channels.
const bare = parseM3u('http://example.invalid/a.m3u8\nhttp://example.invalid/b.m3u8')
assert.equal(bare.length, 2)
assert.equal(bare[0]!.name, 'http://example.invalid/a.m3u8')

// Junk, HTML error pages, and an empty file are all "no channels", never a throw.
assert.deepEqual(parseM3u(''), [])
assert.deepEqual(parseM3u('<html><body>403 Forbidden</body></html>'), [])
assert.deepEqual(parseM3u('#EXTM3U\n#EXTINF:-1,Orphan with no url\n'), [])

// A name with nothing readable in it is decoration, whatever characters it used.
assert.deepEqual(parseM3u('#EXTINF:-1,▓▓▓▓▓▓\nhttp://example.invalid/x'), [])

// --- Finding one channel in ten thousand ---------------------------------------

assert.deepEqual(channelGroups(channels), ['News', 'Sports'])
assert.equal(filterChannels(channels, 'channel', '').length, 2)
assert.equal(filterChannels(channels, '', 'Sports').length, 1)
assert.equal(filterChannels(channels, 'CHANNEL', 'News').length, 1, 'search is case-insensitive')
assert.equal(filterChannels(channels, '', '').length, 3, 'no filter is every channel')

// --- The credential that must not be on screen ---------------------------------

// An Xtream playlist URL carries the account's password in its query string,
// and the settings list gets read across a room.
const xtream = 'http://panel.invalid:8080/get.php?username=bob&password=hunter2&type=m3u_plus'
assert.equal(playlistName(xtream), 'panel.invalid:8080/get.php')
assert.ok(!playlistName(xtream).includes('hunter2'))
// …and out of the backup file entirely.
assert.match(
  read('app/utils/backup.ts'),
  /SECRET = new Set\(\[[^\]]*\$\{PREFIX\}playlists/,
  'ventic.playlists holds a password and must be in backup.ts\'s SECRET set',
)

// --- An Xtream login ------------------------------------------------------------

// Three fields copied out of a provider's email, typed any of the ways they get
// typed, all land on the same stored string — or the duplicate check misses.
const api = 'http://panel.invalid:8080/player_api.php?username=bob&password=hunter2'
for (const server of ['panel.invalid:8080', 'http://panel.invalid:8080/', ' http://panel.invalid:8080/get.php?username=x ', 'http://panel.invalid:8080/c/'])
  assert.equal(xtreamUrl(server, ' bob ', 'hunter2'), api, `server typed as "${server}"`)
assert.equal(xtreamUrl('https://panel.invalid', 'bob', 'p'), 'https://panel.invalid/player_api.php?username=bob&password=p')
assert.equal(xtreamUrl('panel.invalid', 'bob', ''), null, 'no password is no login')
assert.equal(xtreamUrl('ftp://panel.invalid', 'bob', 'p'), null, 'the fetch goes through Rust — http(s) only')
assert.ok(isXtream(api))
assert.ok(!isXtream('http://panel.invalid:8080/get.php?username=bob&password=hunter2&type=m3u_plus'), 'a pasted get.php stays an M3U')
assert.ok(!isXtream('not a url'))
// On screen it is the server, and nothing of the account.
assert.equal(playlistName(api), 'panel.invalid:8080')

const categories = [{ category_id: '1', category_name: 'UK' }, { category_id: 2, category_name: 'Sports' }]
const streams = [
  { name: 'BBC One', stream_id: 11, stream_icon: 'http://example.invalid/bbc.png', category_id: '1' },
  { name: '═══════════', stream_id: 12, category_id: '2' },
  { name: 'Sky Sports', stream_id: '13', category_id: 2 },
  { name: 'No id', category_id: '1' },
  { name: 'Orphan', stream_id: 14, category_id: '99' },
]
const xlive = parseXtream(api, categories, streams, ['m3u8', 'ts'])
assert.deepEqual(xlive.map(c => c.name), ['BBC One', 'Sky Sports', 'Orphan'], 'decoration and id-less rows are dropped')
assert.deepEqual(xlive.map(c => c.group), ['UK', 'Sports', ''], 'a category id is a number in one panel and a string in the next')
assert.equal(xlive[0]!.url, 'http://panel.invalid:8080/live/bob/hunter2/11.ts')
assert.equal(xlive[0]!.logo, 'http://example.invalid/bbc.png')
assert.equal(xlive[1]!.logo, '')
assert.equal(new Set(xlive.map(c => c.id)).size, 3)
// An account that may not have .ts gets HLS; one that says nothing gets .ts.
assert.match(parseXtream(api, [], streams, ['m3u8'])[0]!.url, /\.m3u8$/)
assert.match(parseXtream(api, [], streams, undefined)[0]!.url, /\.ts$/)
// A credential with a slash in it would otherwise be two path segments.
assert.equal(parseXtream(xtreamUrl('panel.invalid', 'a/b', 'p w')!, [], streams, [])[0]!.url, 'http://panel.invalid/live/a%2Fb/p%20w/11.ts')
// A panel's error page instead of JSON is no channels, not a throw.
assert.deepEqual(parseXtream(api, null, { error: 'flood' }, null), [])

// A wrong password and an expired account are both HTTP 200. Only user_info
// tells them from an empty list, and each has to reach the page as a sentence.
async function panel(account: unknown, run: () => Promise<unknown>) {
  const realFetch = globalThis.fetch
  globalThis.fetch = (async (input: string) => {
    const action = new URL(input).searchParams.get('action')
    const body = action === 'get_live_streams' ? streams : action === 'get_live_categories' ? categories : account
    return new Response(JSON.stringify(body))
  }) as typeof fetch
  try {
    return await run()
  }
  finally {
    globalThis.fetch = realFetch
  }
}
await panel({ user_info: { auth: 0 } }, () => assert.rejects(xtreamChannels(api), (e: Error) => {
  assert.match(e.message, /did not accept/)
  assert.ok(!e.message.includes('hunter2'), 'the error names the server, never the password')
  return true
}))
await panel({ user_info: { auth: 1, status: 'Expired' } }, () =>
  assert.rejects(xtreamChannels(api), /says this account is expired/))
await panel({ user_info: { auth: 1, status: 'Active', allowed_output_formats: ['ts'] } }, async () => {
  // Through fetchChannels, beside nothing else: the login and an M3U share one list.
  const got = await fetchChannels([api])
  assert.equal(got.length, 3)
  assert.equal(got[0]!.group, 'UK')
})

// --- Favourites are filed by name, never by URL --------------------------------

// An Xtream stream URL is `…/username/password/12345.ts`, and this map does
// travel in a backup. It also survives a provider rotating its URLs, which they
// do — keying on the URL would silently drop every favourite the day they did.
assert.equal(channelKey('  ESPN HD  '), channelKey('espn hd'))
assert.ok(!channelKey('ESPN').includes('/'))
assert.match(
  read('app/stores/library.ts'),
  /ventic\.liveFavourites/,
  'channel favourites need their own map — everything else there is keyed by titleKey',
)

// --- The two seams no compiler sees --------------------------------------------

// The playlist host sends no Access-Control-Allow-Origin, so the fetch cannot be
// the webview's. Take this away and every playlist fails as a CORS error.
assert.match(
  read('app/utils/iptv.ts'),
  /from '@tauri-apps\/plugin-http'/,
  'the playlist fetch must go through Rust — a webview fetch is bound by CORS',
)
assert.match(
  read('src-tauri/capabilities/main.json'),
  /"http:default"/,
  'the http plugin needs a capability, or its fetch is denied at runtime',
)
assert.match(read('src-tauri/src/lib.rs'), /tauri_plugin_http::init\(\)/)

// DefaultMediaSourceFactory only recognises an .m3u8 with this module on the
// classpath. Without it Android plays no channel at all, and says only that the
// stream could not be read.
assert.match(
  read('src-tauri/gen/android/app/build.gradle.kts'),
  /media3-exoplayer-hls/,
  'Android needs the HLS module or every live channel fails to open',
)

// --- Reading it again ----------------------------------------------------------

// A playlist is fetched once per session, which is the point — and which is
// exactly what the Reload button beside the channel list exists to go past.
// `refresh()` on its own re-runs the handler and is handed the cache straight
// back, so the button did nothing at all: the one press that means "ask the
// panel again" has to reach `loadChannels`' second argument.
const live = read('app/pages/live.vue')
assert.match(
  live,
  /loadChannels\(settings\.playlists, \w+\)/,
  'the Live TV page must be able to load past the once-per-session cache',
)
assert.doesNotMatch(
  live,
  /@click="refresh\(\)"/,
  'Reload and Retry must go through the wrapper that clears the cache, not refresh() alone',
)

// A playlist nobody can read has to reach the page as its own sentence. Wrapped
// in a second Error, the first one's `String()` form *is* the message — so the
// panel's 404 showed as "Error: … answered HTTP 404", the word Error in front
// of a sentence that already read as one.
const realFetch = globalThis.fetch
globalThis.fetch = (async () => new Response('', { status: 404 })) as typeof fetch
try {
  await assert.rejects(fetchChannels(['https://example.invalid/list.m3u']), (e: Error) => {
    assert.ok(!e.message.startsWith('Error:'), `a playlist failure reads as "${e.message}" on the page`)
    assert.match(e.message, /404/, 'and it says what the panel answered')
    return true
  })
}
finally {
  globalThis.fetch = realFetch
}

// A `<script setup>` binding wins over a prop of the same name in the template,
// silently: a local `let live` made the LIVE dot show on every film, because it
// was the mounted flag and not the channel flag being read. Nothing warns.
const player = read('app/components/MpvPlayer.vue')
for (const prop of player.slice(0, player.indexOf('}>()')).matchAll(/^ {2}(\w+)\??:/gm)) {
  assert.doesNotMatch(
    player,
    new RegExp(`^(let|const|var|function)\\s+${prop[1]}\\b`, 'm'),
    `MpvPlayer declares \`${prop[1]}\` twice — the local shadows the prop in the template`,
  )
}

// --- The line this feature does not cross --------------------------------------

// The app ships with no playlists and names none, exactly as it ships with no
// sources. A URL anywhere in here would make this project the one distributing
// it. `example.invalid` above is reserved by RFC 2606 and resolves nowhere.
const shipped = [read('app/utils/iptv.ts'), read('app/pages/live.vue'), read('app/pages/settings/sources.vue')]
for (const file of shipped) {
  const urls = file.match(/https?:\/\/[\w.-]+/g) ?? []
  for (const url of urls) {
    assert.ok(
      /example\.invalid|^https?:\/\/…?$/.test(url) || url === 'http://' || url === 'https://',
      `no playlist or source URL may be shipped, found ${url}`,
    )
  }
}
assert.equal(JSON.parse(read('package.json')).scripts['check:iptv'], 'bun scripts/check-iptv.ts')

console.log('iptv: ok')
process.exitCode = 0
