// Self-check for the Live TV playlist parser: `bun scripts/check-iptv.ts`.
//
// An M3U is generated by somebody else's IPTV panel, is tens of thousands of
// lines long, and reaches a user long before any build does. The parser's whole
// job is to get the readable rows out and drop the rest rather than take the
// page down, so that is what this holds — plus the two things about the *shape*
// of the feature that no compiler sees: the CORS bypass it depends on, and the
// ExoPlayer module without which every channel is unplayable on Android.
import assert from 'node:assert'
import { readFileSync } from 'node:fs'
import process from 'node:process'
import { channelGroups, channelKey, fetchChannels, filterChannels, parseM3u, playlistName } from '../app/utils/iptv'
import './i18n-stub'

const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

// --- The rows a real playlist is made of --------------------------------------

const playlist = `#EXTM3U url-tvg="http://example.invalid/epg.xml"
#EXTINF:-1 tvg-id="one.us" tvg-logo="http://example.invalid/1.png" group-title="Sports",Channel One HD
http://example.invalid/live/one.m3u8
#EXTINF:-1 group-title="Sports",═══════════
http://example.invalid/live/divider
#EXTGRP:News
#EXTINF:-1,Channel Two
#EXTVLCOPT:http-user-agent=SomePlayer/1.0
http://example.invalid/live/two.ts|User-Agent=SomePlayer%2F1.0
#EXTINF:-1 tvg-name="Three, the third" tvg-logo="http://example.invalid/3.png",Ignored Title
http://example.invalid/live/three.m3u8
`

const channels = parseM3u(playlist)

assert.equal(channels.length, 3, 'a row of box characters is decoration, not a channel')
assert.deepEqual(channels.map(c => c.name), ['Channel One HD', 'Channel Two', 'Three, the third'])

// group-title wins where it exists; #EXTGRP carries on until the next one.
assert.deepEqual(channels.map(c => c.group), ['Sports', 'News', 'News'])

// A comma inside a quoted attribute must not be read as the one before the name.
assert.equal(channels[2]!.name, 'Three, the third')
// …and tvg-name beats the display title, which is where a panel puts its junk.
assert.equal(channels[2]!.logo, 'http://example.invalid/3.png')

// `url|User-Agent=…` smuggles request headers past a URL. Nothing here can send
// them, and left on the end they make the URL itself wrong.
assert.equal(channels[1]!.url, 'http://example.invalid/live/two.ts')
assert.equal(channels[1]!.logo, '', 'the previous entry\'s logo must not carry over')

// Ids are unique, or the grid renders one card for two channels.
assert.equal(new Set(channels.map(c => c.id)).size, 3)

// --- Playlists that are barely playlists --------------------------------------

// No #EXTINF at all: a bare list of URLs is still a list of channels.
const bare = parseM3u('http://example.invalid/a.m3u8\nhttp://example.invalid/b.m3u8')
assert.equal(bare.length, 2)
assert.equal(bare[0]!.name, 'http://example.invalid/a.m3u8')

// Junk, HTML error pages, and an empty file are all "no channels", never a throw.
assert.deepEqual(parseM3u(''), [])
assert.deepEqual(parseM3u('<html><body>403 Forbidden</body></html>'), [])
assert.deepEqual(parseM3u('#EXTM3U\n#EXTINF:-1,Orphan with no url\n'), [])

// A name with nothing readable in it is decoration, whatever characters it used.
assert.deepEqual(parseM3u('#EXTINF:-1,▓▓▓▓▓▓\nhttp://example.invalid/x'), [])

// --- Finding one channel in ten thousand ---------------------------------------

assert.deepEqual(channelGroups(channels), ['News', 'Sports'])
assert.equal(filterChannels(channels, 'channel', '').length, 2)
assert.equal(filterChannels(channels, '', 'Sports').length, 1)
assert.equal(filterChannels(channels, 'CHANNEL', 'News').length, 1, 'search is case-insensitive')
assert.equal(filterChannels(channels, '', '').length, 3, 'no filter is every channel')

// --- The credential that must not be on screen ---------------------------------

// An Xtream playlist URL carries the account's password in its query string,
// and the settings list gets read across a room.
const xtream = 'http://panel.invalid:8080/get.php?username=bob&password=hunter2&type=m3u_plus'
assert.equal(playlistName(xtream), 'panel.invalid:8080/get.php')
assert.ok(!playlistName(xtream).includes('hunter2'))
// …and out of the backup file entirely.
assert.match(
  read('app/utils/backup.ts'),
  /SECRET = new Set\(\[[^\]]*\$\{PREFIX\}playlists/,
  'ventic.playlists holds a password and must be in backup.ts\'s SECRET set',
)

// --- Favourites are filed by name, never by URL --------------------------------

// An Xtream stream URL is `…/username/password/12345.ts`, and this map does
// travel in a backup. It also survives a provider rotating its URLs, which they
// do — keying on the URL would silently drop every favourite the day they did.
assert.equal(channelKey('  ESPN HD  '), channelKey('espn hd'))
assert.ok(!channelKey('ESPN').includes('/'))
assert.match(
  read('app/stores/library.ts'),
  /ventic\.liveFavourites/,
  'channel favourites need their own map — everything else there is keyed by titleKey',
)

// --- The two seams no compiler sees --------------------------------------------

// The playlist host sends no Access-Control-Allow-Origin, so the fetch cannot be
// the webview's. Take this away and every playlist fails as a CORS error.
assert.match(
  read('app/utils/iptv.ts'),
  /from '@tauri-apps\/plugin-http'/,
  'the playlist fetch must go through Rust — a webview fetch is bound by CORS',
)
assert.match(
  read('src-tauri/capabilities/main.json'),
  /"http:default"/,
  'the http plugin needs a capability, or its fetch is denied at runtime',
)
assert.match(read('src-tauri/src/lib.rs'), /tauri_plugin_http::init\(\)/)

// DefaultMediaSourceFactory only recognises an .m3u8 with this module on the
// classpath. Without it Android plays no channel at all, and says only that the
// stream could not be read.
assert.match(
  read('src-tauri/gen/android/app/build.gradle.kts'),
  /media3-exoplayer-hls/,
  'Android needs the HLS module or every live channel fails to open',
)

// --- Reading it again ----------------------------------------------------------

// A playlist is fetched once per session, which is the point — and which is
// exactly what the Reload button beside the channel list exists to go past.
// `refresh()` on its own re-runs the handler and is handed the cache straight
// back, so the button did nothing at all: the one press that means "ask the
// panel again" has to reach `loadChannels`' second argument.
const live = read('app/pages/live.vue')
assert.match(
  live,
  /loadChannels\(settings\.playlists, \w+\)/,
  'the Live TV page must be able to load past the once-per-session cache',
)
assert.doesNotMatch(
  live,
  /@click="refresh\(\)"/,
  'Reload and Retry must go through the wrapper that clears the cache, not refresh() alone',
)

// A playlist nobody can read has to reach the page as its own sentence. Wrapped
// in a second Error, the first one's `String()` form *is* the message — so the
// panel's 404 showed as "Error: … answered HTTP 404", the word Error in front
// of a sentence that already read as one.
const realFetch = globalThis.fetch
globalThis.fetch = (async () => new Response('', { status: 404 })) as typeof fetch
try {
  await assert.rejects(fetchChannels(['https://example.invalid/list.m3u']), (e: Error) => {
    assert.ok(!e.message.startsWith('Error:'), `a playlist failure reads as "${e.message}" on the page`)
    assert.match(e.message, /404/, 'and it says what the panel answered')
    return true
  })
}
finally {
  globalThis.fetch = realFetch
}

// --- The line this feature does not cross --------------------------------------

// The app ships with no playlists and names none, exactly as it ships with no
// sources. A URL anywhere in here would make this project the one distributing
// it. `example.invalid` above is reserved by RFC 2606 and resolves nowhere.
const shipped = [read('app/utils/iptv.ts'), read('app/pages/live.vue'), read('app/pages/settings/sources.vue')]
for (const file of shipped) {
  const urls = file.match(/https?:\/\/[\w.-]+/g) ?? []
  for (const url of urls) {
    assert.ok(
      /example\.invalid|^https?:\/\/…?$/.test(url) || url === 'http://' || url === 'https://',
      `no playlist or source URL may be shipped, found ${url}`,
    )
  }
}
assert.equal(JSON.parse(read('package.json')).scripts['check:iptv'], 'bun scripts/check-iptv.ts')

console.log('iptv: ok')
process.exitCode = 0
